<?php

$title = 'Mijn showcases';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Voeg nieuwe showcase toe</a>
</p>

<table class="table">
<tr>
    <th>Showcase</th>
    <th>Onderwerp</th>
    <th>file</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
    <td><?php echo $this->escapeHtml($album->file);?></td>
    <td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
        <a href=
          <?php
          
          $str = str_replace(".zip", "", $album->file);
        
          $filename = "/var/www/html/uploads/".$str."/index.html";
        if (file_exists($filename)) {
           echo 'http://localhost/uploads/'.$str.'/index.html';
        } else {
            echo $this->url('album',array('action'=>'view', 'id' => $album->id));
        }
          
          ?>>View</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
