
 <div class="jumbotron">
      <div class="container">
        <h1>HR showcases!</h1>
        <p>Op deze website kunnen studenten Media Technologie showcases uploaden van hun projecten, die dan kunnen worden bekeken door bezoekers van de Hogeschool Rotterdam locatie wijnhaven.</p>
        <p><a class="btn btn-primary btn-lg" role="button">Schrijf je in &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Onzin</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Andere onzin</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>Onzin plaatje</h2>
          <div class="product-img ">
                   <img class="img-responsive" src="img/imgtest.jpg" alt="" />
          </div>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
